### ISSUE TITLE
Does Not Generate declarations when dir has extended file name with dot notation

### ISSUE THREAD

**Issue by martinmckenna** [vytenisu/npm-dts#2]
First off, this package is awesome so thank you.

Steps to reproduce

1. Init a typescript project and create declaration files with tsc so that you end up with a file structure like

```
- lib
  -account
      - account.d.ts
      - account.js
      - account.schema.js
      - account.schema.d.ts
```

which has been created from 

```
- src
  -account
      - account.ts
      - account.schema.ts
```

2. Run the build (in this case I'm using npm-dts-webpack-plugin).

3. Final index.d.ts file doesn't include the declarations located in account.d.ts

If I rename my `src/account/account.ts` to `src/account/somethingelse.ts`, everything works fine.

What exists in my build `index.d.ts` fille is:

```js
declare module 'my-package/account/account' {
 /** stuff that was inside my account.scheme.d.ts file */
}
```

**Comment by vytenisu** [comment]
Reproduced issue by adding non-exported "a.schema.ts" file into E2E test. Will have a look why this happens.

**Comment by vytenisu** [comment]
Please try updating to 1.1.10 version and let me know if fix works well for you.

**Comment by martinmckenna** [comment]
Works like a charm. Thanks @vytenisu!
