### ISSUE TITLE
Can generate d.ts file of specific dir instead of whole npm packages

### ISSUE THREAD

**Issue by superdc** [vytenisu/npm-dts#23]

**Comment by vytenisu** [comment]
At the moment the main purpose of npm-dts is to generate d.ts for whole npm package. This is the reason why it is called npm-dts. Can I check what the exact use case is? Maybe it is worth splitting package into several or have a single entry point?

**Comment by vytenisu** [comment]
Will be closing this request due to inactivity. Reasoning is that main purpose of **npm-dts** is to allow single-entry-point packages to be typed even if they are pre-bundled and do not contain original source code. For now, I would consider this request to be out of scope for **npm-dts**.
