### ISSUE TITLE
FeatureRequest: Option to change tsconfig.json file for monorepo packages

### ISSUE THREAD

**Issue by romelperez** [vytenisu/npm-dts#28]
## Type

- Feature Request

## Use Case

Assuming a monorepo like this:

```txt
myproject/
    packages/
        packageA/
            src/
                index.ts
            tsconfig.build.json
            package.json
        packageB/
            src/
                index.ts
            tsconfig.build.json
            package.json
    tsconfig.json
    package.json
```

I run the generation with the following options:

```bash
npx npm-dts generate \
  --root ./packages/packageA/ \
  --entry ./packages/packageA/src/index.ts \
  --output ./packages/packageA/index.d.ts \
  --logLevel debug
```

The script generates all packages in the monorepo and they are included in the final file with wrong paths, since it is picking up the root `tsconfig.json` file, instead of specific package TS config file.

## Request

There should be a way to define `tsconfig.json` file, since it may be different than the default filename name.

## Environment

- node v16.14.0
- npm-dts ^1.3.11"
- typescript 4.4.x"

----

Thank you for your work!

**Comment by vytenisu** [comment]
_npm-dts_ uses _TSC_ under the hood and allows forwarding command line arguments to _TSC_ via "--tsc" option. _TSC_ allows overriding project path using "-p" I think. See: https://github.com/microsoft/TypeScript/issues/5858

**Comment by romelperez** [comment]
Hello! It worked, but it has a related bug.

When you pass in the CLI the `--tsc` option like this: `npm-dts generate --tsc "-p tsconfig.build.json"`, the option value gets ignored.

It worked only when I added a space at the beginning of the option value, as you had in your e2e tests: `npm-dts generate --tsc " -p tsconfig.build.json"`.

Now it works. Thank you!

**Comment by vytenisu** [comment]
Awesome. Thanks for confirming the need for space there. I remember this bug and for some reason I thought it was solved :D I will re-open this issue in order not to forget to address it.

**Comment by vytenisu** [comment]
Turns out that there is a bug in sub-module which I use - "args". It treats "-p" as another argument for _npm-dts_... I would either need to manually parse arguments or fix sub-module. I will document this case for now in README
