### ISSUE TITLE
Source maps refer to the compiled file

### ISSUE THREAD

**Issue by maslade** [vytenisu/npm-dts#36]
I am having a hard time getting this to work, but am not receiving errors. I want to step through the code myself to try and find out what I'm doing wrong, but source maps aren't bundled correctly so I'm only able to see minified code. The distributed file is `dist/index.js`, and its map file (`index.js.map`) includes this:

```
{"version":3,"file":"index.js","mappings":...}
```

This is on v1.3.12.

**Comment by vytenisu** [comment]
There seems to be some problem with production build source map. I did not use it myself and therefor did not notice.

You can work-around this problem for now by cloning **npm-dts** and building it for development:
`
git clone git@github.com:vytenisu/npm-dts.git
cd npm-dts
npm install
# add brakepoint somewhere in code
npm run buildDev
npm run exec
`

I tested on my VSCode - brakepoints worked properly when using this approach.

At some point will need to check why it does not work with full build. Maybe minimization ruins things or smth. Also, maybe will add watch one day to avoid building every time :D

**Comment by vytenisu** [comment]
Will close due to inactivity. Basically there is a way to develop conveniently using buildDev.
