### ISSUE TITLE
Error in CRLF line break type

### ISSUE THREAD

**Issue by andrelmlins** [vytenisu/npm-dts#7]
Hello @vytenisu , great project, congratulations.

The file `cli.js` is in the CRLF line break type in the npm package. This results in the following error in MacOS environment:

```
env: node\r: No such file or directory
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

After changing the format, everything worked normally. The repository file is of type LF. I believe it must be something that happened in the publication of the package.

**Comment by vytenisu** [comment]
Thank you. This is unfortunate... Publishing was in fact was performed from Windows machine.
Will check.

**Comment by vytenisu** [comment]
This is interesting actually. I can see that cli.js has CRLF line endings when I download raw tar file and extract it myself. However, if I do npm install on a MAC machine, file is created with LF endings and CLI works well for me. Will try to re-publish sometime soon.

**Comment by vytenisu** [comment]
I have published new version (1.3.1) from MAC. It has LF line endings now. Please check if it works well for you.

Also, it is a bit of a mystery for me right now why it converted to LF for me on MAC and it did not convert for you when performing npm instell.

Can I check what NPM version you are using? Mine on MAC was 6.13.1

**Comment by andrelmlins** [comment]
Thank you. The version ia 1.3.0, using the yarn. See the job. https://github.com/recifejs/recife/pull/30/checks?check_run_id=912496119

**Comment by vytenisu** [comment]
Got it. Looks like NPM is doing some additional magic hence I did not notice the problem. Maybe will add some build/publish blocking test before release for the future to avoid such problem.
